apiVersion: v1
kind: Service
metadata:
  name: hippocamp-service
spec:
  selector:
    app: hippocamp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer