apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: infrastructure/app-of-apps/ray-operator
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sregpt
  syncPolicy:
    syncOptions:
    - CreateNamespace=true