name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        # NGC Auth Token
        NGC_AUTH_TOKEN: ${{ secrets.NGC_OAUTH_TOKEN }}
      run: |

        echo "$NGC_OAUTH_TOKEN" | docker login nvcr.io --username \$oauthtoken --password-stdin 

        docker build . --file ./backend/Dockerfile --tag edhenry/sregpt:$(date +%s)