name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_REPOSITORY: edhenry/sregpt
  IMAGE_TAG: v0.1.0

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        # NGC Auth Token
        NGC_OAUTH_TOKEN: ${{ secrets.NGC_OAUTH_TOKEN }}
      run: |

        echo "$NGC_OAUTH_TOKEN" | docker login nvcr.io --username \$oauthtoken --password-stdin 
        DOCKER_BUILDKIT=0 docker build . --file ./backend/Dockerfile --tag "$IMAGE_REPOSITORY":"$IMAGE_TAG"
        docker push "$IMAGE_REPOSITORY":"$IMAGE_TAG"

        # Clean artifacts from whatever worker we're using...
        docker rmi "$IMAGE_REPOSITORY":"$IMAGE_TAG"
        docker buildx purge -f